### ISSUE TITLE
Mismatch between number of images and corresponding mano files

### ISSUE THREAD

**Issue by anjugopinath** [zc-alexfan/arctic#13]
I want to use the mano files, but I noticed that there is a mismatch between number of files:

Ex) Within this particular folder, there are 733 images.
![image](https://github.com/zc-alexfan/arctic/assets/4654298/b9c030e5-7454-44db-bfe8-0c57ad590cee)

But, the number of mano files are only 732 (unpack/arctic_data/data/raw_seqs/s01/box_grab_01.mano.npy):
<img width="217" alt="image" src="https://github.com/zc-alexfan/arctic/assets/4654298/26f01e8d-34fc-464e-abc7-1ac58edcf63e">

 Since the mano file does not have information about which image each row maps to, instead of discarding the one image for which the mano parameters are missing, I would have to discard all the images in this folder. 
I wanted to confirm this is the case or if there was an error when downloading the files.
Thank You!

**Comment by zc-alexfan** [comment]
There is no error. The mocap files (MANO groundtruth) are usually 1 or 2 frames off from the image files. This is because we need to synchronize the two systems. 

The synchronization is specified [here](https://github.com/zc-alexfan/arctic/blob/2192e89afe7cebe3010f591b7a383b7f18457862/src/datasets/arctic_dataset.py#L40)

**Comment by anjugopinath** [comment]
Hi,

Thank You for your response. This answers my question!
I just wanted to confirm the logic with an example:

Say, the number of images are 5 and the number of rows in the corresponding mano file is 4 (0,1,2,3).
And say ioi_offset is 2.
And image indexes start with 1 (1.jpg).
So, for the first image, 1-2=-1 (the last row from the mano file will be picked).
And similarly, for the other images:
2-2=0 -> 0th row
3-2=1 -> 1st row
4-2=2 -> 2nd row
5-2=3 -> 3rd row

**Comment by zc-alexfan** [comment]
yes, exactly

**Comment by anjugopinath** [comment]
Thank You for the quick response!

**Comment by anjugopinath** [comment]
Hi,

For the image
unpack/arctic_data/data/images/s01/ketchup_grab_01/1/00655.jpg:

img_id is :  655  offset is :  1   and so index =655-1=  654
And size of pose parameters is 
pose_all_l size is :  (654, 45)

so it's trying to index into the 654th location which throws and error since the pose dictionary length is 654 (0...653) and
so the last row is at index 653.

**Comment by zc-alexfan** [comment]
Currently at cvpr so i have limited capacity. It only happens at a few frames at the end of the sequences. So it won't affect your training.

I will take a look after cvpr

**Comment by zc-alexfan** [comment]
You can check the image folder and see if the images that are missing annotation at the final 1 or 2 frames. If that's the case, then it is fine.

We have two capture systems to synchronize: RGB system, MoCap system. They are off by 1 or 2 frames because we need to take into the account of the camera shutter for the two systems during the capture. So they won't have exactly the same number of frames and off by 1 or 2.

You can reopen the issue if it is not resolved.
