### ISSUE TITLE
Questions for the image resize details

### ISSUE THREAD

**Issue by dongho-Han** [zc-alexfan/arctic#30]
Thanks for the nice work!
I really appreciate reading your paper and baseline code.
And after following your code, I got several questions to ask.

1. 
From the cropped images to go through encoder(ResNet50), the image size should be changed into 1000x1000 -> 224x224. 
I found that process happens from this line,
https://github.com/zc-alexfan/arctic/blob/7e3f736a95d7c461dbd93068de4367374c68a5ac/src/datasets/arctic_dataset.py#L168
And, in data_utils, rgb_processing function does that work.
But, I couldn't understand what does the function really do.
From the generate_patch_image function, I found the affine transformation happens, but couldn't get its meaning. Would you explain these in more detail?
Also, could you elaborate why you did does affine transformation instead of resizing? I thought only resizing the cropped_image into 224*224 is enough.

2. 
Could you explain how the bbox is determined? From below description, I could understand what the bbox is, but I got curious how you determined the bbox values. If I try to use another dataset, I think I have to determine bbox variable.
From 'data_doc.md',
data_dict - s05/box_use_01 - bbox: Bounding box (squared) on image for network input; three-dimensional cx, cy, scale where (cx, cy) is the bbox center; scale*200 is the bounding box width and height; frames x views x 3

3.
In scripts_data/crop_images.py, process_fname function is used for cropping. 
https://github.com/zc-alexfan/arctic/blob/7e3f736a95d7c461dbd93068de4367374c68a5ac/scripts_data/crop_images.py#L35
Could you explain the details why the ego_image_scale == 0.3?

~~4.~~
~~[Solved]I misread the code, and asked dumb question.~~

**Comment by zc-alexfan** [comment]
Thanks for your interest in our dataset.

1. Affine transformation is more general as it can represent rotation, translation, cropping, resizing in the 2d image space. We use affine transformation because I was using some of InterHand2.6M code.

2. You can refer to the preprocessing code [here](https://github.com/zc-alexfan/arctic/blob/7e3f736a95d7c461dbd93068de4367374c68a5ac/src/arctic/processing.py#L55)

3. The images are 2k-resolution. It is extremely slow to load images. So for egocentric images, I just resize them to smaller. The value is arbitrary.
