### ISSUE TITLE
Possible inconsistency in the MoCap labels?

### ISSUE THREAD

**Issue by heydarshahi** [zc-alexfan/arctic#38]
Working on the MoCap data, I noticed some labels are not the same for different subjects. An example of this is: 
The markers on the base of the table correspond to `[M_1, M_2, M_5, M_6]` for subjects s01 through s04 and `[M_5, M_6, M_7, M_8]`for subjects s05 and s06. 

Is there a part of the data that specifies which labels correspond to which markers?
Of course, this might be a problem with my visualization, in which case I'd appreciate it if you could confirm that the labels correspond to the same markers across the subjects.

Thanks!
Amin

**Comment by zc-alexfan** [comment]
Hi @heydarshahi, I don't remember the precise details because the data was captured 2 years ago. But it is possible that it is inconsistent because there are several markersets for the table and during the capture we might have used different names. 

I would suggest to use our [mocap viewer](https://github.com/zc-alexfan/arctic/blob/master/scripts_data/mocap_viewer.py) to check the names of the table markers to see. 

I don't think the relative distances between the table markers will change in the capture because they were glued on the table (at least the ones that are at the top of the table). To verify the markers relative locations are unchanged, you can compute pair-wise distance between markers in different captures and see if the pair-wise distances are the same in all captures. 

Hope it helps.
