### ISSUE TITLE
ArcticSF on HO3D

### ISSUE THREAD

**Issue by heydarshahi** [zc-alexfan/arctic#45]
Hi and thanks for the awesome HOLD code release! 

I wonder if you have also tried adapting Arctic models to work with HO3D without an off-the-shelf pose estimator?

Best,
Amin

**Comment by zc-alexfan** [comment]
It was asked in one of our reviewer question when we submitted ARCTIC. In general, it won't work because you need to align the canonical space of ARCTIC and HO3D objects, then the object 6d poses will be consistent across datasets. 

We tried an experiment where we pretrain on ARCTIC and finetune on HO3D and it helped a bit with the object pose estimation.

**Comment by zc-alexfan** [comment]
1. Yes, the ArcticNetSF model should be able to estimate hand poses regardless of object type. 
2. 23cm seems like an obvious error somewhere (our hand is around 15cm; imagine if we randomly select 3d points on your hand, it will be lower than 23cm). If you are computing root-relative MPJPE, you should subtract hand joints by its root.

**Comment by heydarshahi** [comment]
The 23cm is the mean joint/vertex distances of the right hand. However, we don't subtract the means and that's why the number is much higher than the root-relative MPJPE. 

Thanks for the response! Please feel free to close the issue :)
